version: '3.7'
services:
  refbox:
    container_name: refbox
    image: "${REFBOX_IMAGE}:${REFBOX_TAG}"
    network_mode: "host"
    depends_on:
      - mongodb
    restart: "on-failure"
    command: llsf-refbox --dump-cfg
    volumes:
      - ${REFBOX_CONFIG_GAME}:/etc/rcll-refbox/game/default_game.yaml:z
      - ${REFBOX_CONFIG_SIMULATION}:/etc/rcll-refbox/simulation/defaultA_simulation.yaml:z
      - ${REFBOX_CONFIG_COMM}:/etc/rcll-refbox/comm/default_comm.yaml:z
      - ${REFBOX_CONFIG_MPS}:/etc/rcll-refbox/mps/default_mps.yaml:z
      - ${REFBOX_CONFIG_TEAM}:/etc/rcll-refbox/team/default_team.yaml:z
      - ${REFBOX_CONFIG_CHALLENGE}:/etc/rcll-refbox/challenges/default_challenges.yaml:z
      - ${REFBOX_CONFIG_MONGODB}:/etc/rcll-refbox/mongodb/default_mongodb.yaml:z

  frontend:
    container_name: refbox-frontend
    image: "${REFBOX_FRONTEND_IMAGE}:${REFBOX_FRONTEND_TAG}"
    network_mode: "host"
    restart: "no"
  mongodb:
    container_name: "mongodb"
    network_mode: "host"
    image: mongo
    restart: "no"
    volumes:
      - './data:/data/db:z'
